services:
  vhost:
    image: jwilder/nginx-proxy:alpine
    ports:
      - '80:80'
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  maildev:
    image: djfarrelly/maildev
    environment:
      VIRTUAL_HOST: mail.127.0.0.1.nip.io
      VIRTUAL_PORT: 80
    ports:
      - '1025:25'

  backend:
    build: .
    environment:
      OAUTH_GOOGLE_ID: 'YOUR_GOOGLE_ID'
      VIRTUAL_HOST: api.127.0.0.1.nip.io
      JWT_SECRET_BASE64: 'LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb3dJQkFBS0NBUUVBelhkczJXOVB1bTlScVlXREhSa1c4eGh1eDdaSUV3SWNBWWNwTHNVTDNCeVFObGJ1CmRPQW5CUFovZmVKb244dHd0d1JUNzJCSkRhRkxjSHowTFFrT3VUd29XYnBkRDJ6ekRkek1JYUVzQlBXMmFSVHYKMzZIQUU3Z1Zjb2Vwb0pCR1NVdU5mK2sra1o3OUFTT2dQT2RKeW1aYmc2aDFiaTRlRzh5NnFBRDJUcG5CUzVuWgpNZS9CVitRa2ZyQ1RjTHhqWlliSUFOeEFXckFOTndCUklNVGR5ZVRFMlM0TFdkeTVSVEhUejFjUlJqMVVrUURxCnBDcDh0SEtXSkZKUEJ6WDFSMWtkSUZBVWlEa1BUQnRzVW1Yc3lZOS8yNUozUWZnZmJiOE1obDdJMWwrTVdyQWMKenR4MHFrNnBKdEhKSVZVTjlkSFB2WEt1dVFRRDdhc0RPTXhTVXdJREFRQUJBb0lCQUNreFB6WmNkWnlJQXRROAp1eXVUUXlHYmpXSW1yazU1UnNvYm9lc0pnRFl4MTh1OUkvTjBtUDRLdVVhd3BJOGN4MDA1NWVZQTVNU0J5TkVWCmpCS1hWVWRYd3pNeUJNUTU4SVNmOXFEcllocmdkQ0NmSFBRMXhuOXRrWWN6b1pOYU9XMHFZNFQ0YXgzZ3hSSjgKWlB5dzFmOXBCQUhpUFNESXlDcUVvZ3RhbmdibHVuNEtZTUpuWkdrNjFNWnBYcnhyRFN5dDUxRS84TXdacVdZcwpSSTVCTFFNbE05cVFrNGM2Q1pubGI5Z05hQnZoQ0h2QWJnc0FpUkhKeEUvZlY4Q2k5bXFsemdkUU9ZVmNWcUNyCmprcThEREREWG5kbko3TkxzWjBEbWFGcGQ5UGZrcTd5MGRUZU5JNU9iaVV1b0NaSFk1cWQvdVMwME9BRVBuTWsKeE80V0gra0NnWUVBNkZqWFh2WFlacGZxVUVCU2diQ0lnVUkweFNMREVBMjFSbnlaYkNFZE9HeTJxQWJxa2xjdwpmVkNxd3p6Y1VhUDhMYmtxRnBUVHM1dU1ZY2hRQ09CRWdKY0pXMTdiRmlNM3ZRblhEVTlLRkxWYjVLTXA2cU5QCmxSR2ZYanljc0g4K1dlNTUyVUZzNEEvZlpSdjRGbGcvM3IreGRJM1AxbjZid2JTRkpEUUs5TWNDZ1lFQTRtSU8KQUZQbHozSml6d1JtV044V3cwTFlDcU9CU21pUFdmUEo2dHBvSDN1NkVPYlVqSENYSXV0b2lkUzRXcENaYURkUAo5dG1TU2NoYkRFbXpYd2lYdXlaL1B1RW5DcU41T2Roak53dDY4bUxPL0pFV1hTWGpsQ1dCaVVtdHB0YnEwMmlkCit6dnFCMjZPbGxTdC9VWkx1T3lRREVNbExsNitHSlFUVFM4TjBoVUNnWUJCVDZmS282U2V3aGsxVWI5ZmdUWDkKejVSeHphR3pRNGN2TnhzUlVBV2N0TUpyWFBaWENIY3k0cGY5cFgvdzJ2MnFCS0NXRkdPbDJ4V003dmZBWnZvYQpnMW8zK3VQdXh4dUY0ZHczZTVCQlhmRmt4WkNreWg4MnNldHdXKzFYbDR6NVRwV2x3a1JPZjJlMlRqUmdZNUlnCmxSWFd3MzRtdHhRbFVROFQ3Q1VnUlFLQmdEU1V2ZGZKcE5rWUltY2ZDSDZmNG5PYjlQNFRtQlltVHhWL2tHaWkKTGdrUi9kZXJKYmN3OTRtK3o5c2pzMllscTl3TzdOM1REeTFnQWZYS3NJVGtSQW5PR1VRTG03dlcySE5kRlQ1Vgp4a3JDTkgxcFhaNXBESUQrYlNYc0hROWhYODJXd1FyM2taWUVVYzROQVJTUTNVbW9lSlRBaThSSGNUUFlRTnR1CmtIRTVBb0dCQU1HbFd2M1BaOHJxcEl0RUxtUUJpSEtPVU4yL1NxbDZWSFFUbkQ0Q2cwZUtiQmJPQ3hDbU0rWmMKeFV6cnJWMmUrLzlDV2RmK1FETlBxWFByeWdBa2hBMGdNZGdDR2xEN3dyVktEZjRPSFRYZ0tNU2YzYzBuNC91RQpna1FVeFJUQ1RQOFJidWttazc3WFhwZFBVNS84Q1UvdE0vcmYwSFB4Ry8yaXZiQTNSaE4zCi0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg=='
      JWT_JWKS_URL: 'http://backend:5000/auth/.well-known/jwks.json'
      JWT_TTL: '1h'
      DATABASE_URL: 'postgresql://admin:postgres@database:5432/dev?schema=development'
    depends_on:
      - database

  database:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'dev'
    ports:
      - '5432:5432'
    volumes:
      - postgresql:/var/lib/postgresql/data

volumes:
  postgresql:
